#version 460
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba32f) uniform writeonly image2D image_output;

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image_output);
    
    if(p.x < size.x && p.y < size.y)
    {
        float brightness = float((p.x^p.y)%256)/256.0f;
        imageStore(image_output, p, vec4(brightness));
    }
}

